[package]
name = "tba"
version = "0.1.0"
edition = "2024"
authors = ["Trevor Sears <trevor@trevorsears.com>"]
description = "An async Rust client for The Blue Alliance API."
readme = "README.md"
license = "LGPL-3.0-or-later"
documentation = "https://docs.rs/tba"
repository = "https://github.com/AthenaFRC/tba"
keywords = ["frc", "first-robotics", "the-blue-alliance", "api", "async"]
categories = ["api-bindings", "web-programming::http-client"]

[lib]
name = "tba"
path = "src/lib.rs"

[features]
default = []
rate-limit = ["dep:governor"]
cli = ["dep:clap", "dep:clap_complete", "dep:toml"]

[[bin]]
name = "tba"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
paste = { version = "1.0.15" }
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.145" }

dotenvy = "0.15.7"

governor = { version = "0.10.4", optional = true }
clap = { version = "4.6.6", features = ["derive", "string", "wrap_help"], optional = true }
clap_complete = { version = "4.6.9", optional = true }
toml = { version = "1.1.4+spec-1.1.0", optional = true }

[build-dependencies]
clap = { version = "4.6.6", features = ["derive", "string", "wrap_help"], optional = true }
clap_complete = { version = "4.6.9", optional = true }
