use quote::quote;

use crate::models::Model;

pub fn render(
	models: &[Model],
	spec_path: &str,
	api_version: &str,
) -> Result<String, String> {
	let items = models.iter().map(Model::render);
	let tokens = quote! {
		#(#items)*
	};
	let file = syn::parse2::<syn::File>(tokens).map_err(|error| {
		format!("generated models are not valid Rust syntax: {error}")
	})?;
	let items = file
		.items
		.into_iter()
		.map(|item| {
			prettyplease::unparse(&syn::File {
				shebang: None,
				attrs: Vec::new(),
				items: vec![item],
			})
		})
		.collect::<Vec<_>>()
		.join("\n");

	Ok(format!(
		"// @generated by `cargo run -p tba-codegen -- generate`; do not edit.\n\
		 // Source: {spec_path} (TBA API v{api_version}).\n\n\
		 {items}"
	))
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::inputs::spec::Schema;
	use crate::models::StringEnum;

	#[test]
	fn output_is_deterministic_and_valid_rust() {
		let schema: Schema =
			serde_json::from_str(r#"{ "type": "string", "enum": ["a\"b"] }"#)
				.unwrap();
		let model_items = vec![Model::StringEnum(
			StringEnum::parse("Example", &schema, None).unwrap(),
		)];

		let first =
			render(&model_items, "openapi/spec.json", "3.16.0").unwrap();
		let second =
			render(&model_items, "openapi/spec.json", "3.16.0").unwrap();
		assert_eq!(first, second);
		assert!(
			first.contains("// Source: openapi/spec.json (TBA API v3.16.0).")
		);
		assert!(first.contains("#[serde(rename = \"a\\\"b\")]"));
		syn::parse_file(&first).unwrap();
	}
}
